### ISSUE TITLE
Error installing fable.prophet

### ISSUE THREAD

**Issue by cgoo4** [mitchelloharawild/fable.prophet#14]
Hi - I'm getting this error installing `fable.prophet`.  I have `fabletools` 0.1.1.9000 installed.

```r
* installing *source* package ‘fable.prophet’ ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
Failed to create bus connection: Permission denied
Error: package or namespace load failed for ‘fabletools’:
 .onLoad failed in loadNamespace() for 'anytime', details:
  call: system("timedatectl", intern = TRUE)
  error: (converted from warning) running command 'timedatectl' had status 1
Error: package ‘fabletools’ could not be loaded
Execution halted
ERROR: lazy loading failed for package ‘fable.prophet’
```

**Comment by mitchelloharawild** [comment]
Looks as if this is due to a permissions problem specific to your system. Using the CRAN version of fabletools should be sufficient, could you try this?

**Comment by cgoo4** [comment]
Thanks for the suggestion.  I'm using RStudio within IBM Watson Studio, and have tried re-installing all packages from CRAN (including `fabletools 0.1.1`, but then get the same message for fable.prophet.  I've raised a ticket with the Watson Studio team so will update if they have a fix.

**Comment by cgoo4** [comment]
Watson Studio Close notes:  

The R version used in Watson studio is 3.6.1 and the platform in which it runs is Debian GNU/Linux 9.  "fable.prophet" package has a maximum version compatibility of R 3.6.0 for Linux based OS. You can check the version compatibilities of the package here : https://github.com/mitchelloharawild/fable.prophet/blob/master/cran-comments.md . I would recommend you to open an issue with the fable.prophet team/github to support R 3.6.1 for Linux based OS.

**Comment by mitchelloharawild** [comment]
I'm currently running R 3.6.1 on a Linux based OS without issue, and the CI is testing across a variety of R versions and operating systems.

From the error above:

> Failed to create bus connection: Permission denied
> Error: package or namespace load failed for ‘fabletools’:
> .onLoad failed in loadNamespace() for 'anytime', details:
>  call: system("timedatectl", intern = TRUE)
>  error: (converted from warning) running command 'timedatectl' had status 1

This would suggest to me that IBM Watson Studio does not allow you to run `system("timedatectl", intern = TRUE)`, which is causing the `anytime` package to error. Could you try running `system("timedatectl", intern = TRUE)` yourself and see what you get?

**Comment by cgoo4** [comment]
Thanks Mitchell.  Ran per below.  Will raise with the Watson team:

```
system("timedatectl", intern = TRUE)
Failed to create bus connection: Permission denied
character(0)
attr(,"status")
[1] 1
Warning message:
In system("timedatectl", intern = TRUE) :
  running command 'timedatectl' had status 1
```

**Comment by mitchelloharawild** [comment]
Closing as this is not an issue with the package.
Good luck with the Watson team.
